### ISSUE TITLE
Not compatible with IntelliJ IDEA 2023 version of IDE

### ISSUE THREAD

**Issue by DenisBogatirov** [nEdAy/Flutter-Toolkit#10]
Toolbar disappeared and IDE shows warning message on launch that plugin is not compatible.

**Comment by nEdAy** [comment]
Sorry, no time to follow this issue recently, if possible, you can provide PR.

**Comment by dhruvanbhalara** [comment]
Hello @DenisBogatirov,
can you please share the version information of IDE?

**Comment by DenisBogatirov** [comment]
@dhruvanbhalara 
IntelliJ IDEA Ultimate 2023.1.3

**Comment by omralcrt** [comment]
To add action buttons to the toolbar:
Android Studio > Settings > Appearance & Behavior > Menus and Toolbars
In this menu, select Main Toolbar Left, Right, or Center.
Click "+" button and select "Add Action"
Select Plugins > Flutter-Toolkit and click "OK"
Then, apply changes.

You will see the actions there.
You can also add actions one by one instead of as a folder.
